content_image: ./data/content/sir_isaac_newton.jpg
style_image: ./data/style/jaune_rouge_bleu.jpg
output_path: ./results

image_size: 512
steps: 300

alpha: 1.0
beta: 1000000.0

content_layers:
  - conv5_2

style_layers:
  - conv1_1
  - conv2_1
  - conv3_1
  - conv4_1
  - conv5_1