content_image: ./data/content/sir_isaac_newton.jpg
style_image: ./data/style/les_demoiselles_dAvignon.jpg
output_path: ./results

image_size: 512
steps: 300

alpha: 1.0
beta: 10000.0

content_layers:
  - conv4_2

style_layers:
  - conv1_1
  - conv2_1